### ISSUE TITLE
present donate: 轻山科技 2000元 20170809 企业赞助 

### ISSUE THREAD

**Issue by Shidou** [Hangzhou-Node-Party/JS-OpenSource-Foundation#16]
轻山科技 支持杭州 NodeParty 开源基金会为新技术原创技术内容的贡献。

**Comment by xinyu198736** [comment]
感谢支持，已经收款
 ![](https://github.com/Hangzhou-Node-Party/JS-OpenSource-Foundation/raw/master/img/donate-10.jpeg)
