### ISSUE TITLE
present donate: 20170802  8月 node party 请大家喝饮料  150元

### ISSUE THREAD

**Issue by Keith-CY** [Hangzhou-Node-Party/JS-OpenSource-Foundation#2]
杭州 node party 群里 - 银龙の背

**Comment by xinyu198736** [comment]
收到付款，已经记录到赞助列表和收入记录 ，感谢@Keith-CY ![](https://github.com/Hangzhou-Node-Party/JS-OpenSource-Foundation/raw/master/img/donate-1.jpeg)
