### ISSUE TITLE
Present Donate: 20170810 兔耳日记 500

### ISSUE THREAD

**Issue by xiaojue** [Hangzhou-Node-Party/JS-OpenSource-Foundation#20]
[兔耳日记](www.tuer.me) 团队 发来贺电！

当然目前团队只有我一个~~hiahia。

**Comment by xiaojue** [comment]
![tuer](https://user-images.githubusercontent.com/289225/29166621-c224408c-7df9-11e7-81bb-39622af39a1e.png)

**Comment by xinyu198736** [comment]
感谢支持，已经收款
 ![](https://github.com/Hangzhou-Node-Party/JS-OpenSource-Foundation/raw/master/img/donate-13.jpeg)
