### ISSUE TITLE
Present Donate: ${2017.8.10} ${一枚小前端---杀生丸} ${100}

### ISSUE THREAD

**Issue by 5265liu** [Hangzhou-Node-Party/JS-OpenSource-Foundation#21]
个人开发者，赞助下芋头的活动
手机 18536827026
微信 lww1928

**Comment by xinyu198736** [comment]
感谢支持，已经收款
 ![](https://github.com/Hangzhou-Node-Party/JS-OpenSource-Foundation/raw/master/img/donate-14.jpeg)
