### ISSUE TITLE
Present Donate: 20170814 jysperm 200

### ISSUE THREAD

**Issue by jysperm** [Hangzhou-Node-Party/JS-OpenSource-Foundation#24]
文字请显示成「王子亭」，头像如下

![image](https://user-images.githubusercontent.com/1191561/29270235-590ca6c0-8128-11e7-89e7-731273dc3ca5.png)

**Comment by xinyu198736** [comment]
感谢支持，已经收款
 ![](https://github.com/Hangzhou-Node-Party/JS-OpenSource-Foundation/raw/master/img/donate-18.jpeg)
