### ISSUE TITLE
Present Donate: 20170814 老雷 233

### ISSUE THREAD

**Issue by leizongmin** [Hangzhou-Node-Party/JS-OpenSource-Foundation#25]
![image](https://user-images.githubusercontent.com/841625/29272321-14fc1dc6-8132-11e7-93db-4a85d4ec94c5.png)

**Comment by xinyu198736** [comment]
感谢支持，已经收款
 ![](https://github.com/Hangzhou-Node-Party/JS-OpenSource-Foundation/raw/master/img/donate-19.jpeg)
