### ISSUE TITLE
donate: 20170802 祝nodeparty 越办越好 200.88 

### ISSUE THREAD

**Issue by longtianye** [Hangzhou-Node-Party/JS-OpenSource-Foundation#3]
donate: 20170802 祝nodeparty 越办越好 200.88

**Comment by xinyu198736** [comment]
收到付款，已经记录到赞助列表和收入记录 ，感谢@longtianye
 ![](https://github.com/Hangzhou-Node-Party/JS-OpenSource-Foundation/raw/master/img/donate-2.jpeg)
