### ISSUE TITLE
Present Donate: 20170814 点我达大前端 200 团队赞助

### ISSUE THREAD

**Issue by marshalYuan** [Hangzhou-Node-Party/JS-OpenSource-Foundation#30]
[点我达大前端](https://github.com/dwd-fe) 祝贺Node-Foundation成立

**Comment by xinyu198736** [comment]
感谢支持，已经收款
 ![](https://github.com/Hangzhou-Node-Party/JS-OpenSource-Foundation/raw/master/img/donate-21.jpeg)
