### ISSUE TITLE
present donate: 20170815 个人名义赞助 200元

### ISSUE THREAD

**Issue by DevinXian** [Hangzhou-Node-Party/JS-OpenSource-Foundation#36]
支持杭州 Node-Party，希望能越办越好，给大家带来更多的交流学习机会。

**Comment by xinyu198736** [comment]
感谢支持，已经收款
 ![](https://github.com/Hangzhou-Node-Party/JS-OpenSource-Foundation/raw/master/img/donate-26.jpeg)
