### ISSUE TITLE
Present Donate: 2017年08月19日15  北京Node-Party成员祝杭州Node-Party顺利  288.88元 Sunil

### ISSUE THREAD

**Issue by SunilWang** [Hangzhou-Node-Party/JS-OpenSource-Foundation#38]
Present Donate: 2017年08月19日15  北京Node-Party成员祝杭州Node-Party顺利  288.88元 支付宝-Sunil

**Comment by xinyu198736** [comment]
感谢支持，已经收款
 ![](https://github.com/Hangzhou-Node-Party/JS-OpenSource-Foundation/raw/master/img/donate-29.jpeg)
