### ISSUE TITLE
Apply Spending: 20170819 杭州第四期nodeparty讲师住宿和聚餐等费用 1997.5元

### ISSUE THREAD

**Issue by xinyu198736** [Hangzhou-Node-Party/JS-OpenSource-Foundation#40]
费用明细：

1. 顾同学的住宿费一晚 237。00 元。
2. 零食费用 825.50 元
3. 晚上讲师聚餐 935.00 元

共 1997.50 元

发票：

<img src="https://assets.souche.com/assets/sccimg/others/20170829/WechatIMG138.jpeg" width=300/>
<img src="https://assets.souche.com/assets/sccimg/others/20170829/WechatIMG139.jpeg" width=300/>
<img src="https://assets.souche.com/assets/sccimg/others/20170829/WechatIMG140.jpeg" width=300/>

**Comment by Glowin** [comment]
OK

**Comment by ShiningRay** [comment]
OK，感谢！

**Comment by xinyu198736** [comment]
已经打款
 ![](https://github.com/Hangzhou-Node-Party/JS-OpenSource-Foundation/raw/master/img/out-1.jpeg)
