### ISSUE TITLE
present donate: 20170806 个人名义赞助 1024 元

### ISSUE THREAD

**Issue by huanglong** [Hangzhou-Node-Party/JS-OpenSource-Foundation#6]
杭州 NodeParty 微信群 && NodeParty 讲师微信群： Scott 寒冬将至

赞助主要来自 [慕课网视频](http://www.imooc.com/t/108492) 收入

2017.8.19 团队 Outing，不能参加了，祝愿杭州 NodeParty 越办越好

**Comment by xinyu198736** [comment]
收到付款，已经记录到赞助列表和收入记录 ，感谢@huanglong
 ![](https://github.com/Hangzhou-Node-Party/JS-OpenSource-Foundation/raw/master/img/donate-4.png)
