### ISSUE TITLE
income: 掘金 2000元 20170808 企业赞助 掘金发来贺电！

### ISSUE THREAD

**Issue by Glowin** [Hangzhou-Node-Party/JS-OpenSource-Foundation#9]
掘金支持杭州 NodeParty 开源基金会为新技术原创技术内容的贡献。

[掘金 - 一个帮助开发者成长的社区](https://juejin.im)

**Comment by iwillwen** [comment]
感谢江江！感谢掘金的支持！

**Comment by xinyu198736** [comment]
收到付款，已经记录到赞助列表和收入记录 ，感谢@掘金
 ![](https://github.com/Hangzhou-Node-Party/JS-OpenSource-Foundation/raw/master/img/donate-8.jpeg)
